language:
  - swift
osx_image: xcode10.2
xcode_scheme: SpearmintTests
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone XR

before_install:
    - rvm use system
    - sudo gem install cocoapods -v '1.2.0'

